// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QSmartBackend.Models;

public partial class QSmartDBContext : DbContext
{
    public QSmartDBContext(DbContextOptions<QSmartDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Reading> Readings { get; set; }

    public virtual DbSet<Session> Sessions { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Reading>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.SessionId, e.Region });

            entity.Property(e => e.UserId)
                .HasMaxLength(50)
                .HasColumnName("UserID");
            entity.Property(e => e.SessionId)
                .HasMaxLength(50)
                .HasColumnName("SessionID");
            entity.Property(e => e.AccelXyz)
                .HasMaxLength(100)
                .HasColumnName("AccelXYZ");
            entity.Property(e => e.ActivityLabel).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.GyroDps).HasMaxLength(100);
            entity.Property(e => e.Region).HasMaxLength(100);

            entity.HasOne(d => d.Session).WithMany(p => p.Readings)
                .HasForeignKey(d => d.SessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Readings_Sessions");

            entity.HasOne(d => d.User).WithMany(p => p.Readings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Readings_Users");
        });

        modelBuilder.Entity<Session>(entity =>
        {
            entity.ToTable("Sessions", "dbo");
            entity.HasKey(e => e.SessionId).HasName("PK__Sessions__C9F49270D233115A");

            entity.Property(e => e.SessionId)
                .HasMaxLength(50)
                .HasColumnName("SessionID");
            entity.Property(e => e.ActivityLabel).HasMaxLength(100);
            entity.Property(e => e.Region).HasMaxLength(100);
            entity.Property(e => e.StartedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("UserID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}