// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QSmartBackend.Models;

public partial class Reading
{
    public string UserId { get; set; }

    public string SessionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Region { get; set; }

    public double? TensionScore { get; set; }

    public double? HeartRateBpm { get; set; }

    public double? PostureAngleDegree { get; set; }

    public string ActivityLabel { get; set; }

    public double? SkinTempC { get; set; }

    public double? GsrUs { get; set; }

    public double? RespirationBpm { get; set; }

    public double? Spo2Pct { get; set; }

    public double? EmgUv { get; set; }

    public string AccelXyz { get; set; }

    public string GyroDps { get; set; }

    public double? PressureKpa { get; set; }

    public double? AmbientTempC { get; set; }

    public double? HumidityPct { get; set; }

    public double? NoiseDb { get; set; }

    public double? StressIndex { get; set; }

    public double? CumulativeTensionLoad { get; set; }

    public double? RecoveryScore { get; set; }

    public virtual Session Session { get; set; }

    public virtual AppUser User { get; set; }
}