// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QSmartBackend.Models;

public partial class Session
{
    public string SessionId { get; set; }
    
    public string UserId { get; set; }
    public DateTime? StartedAt { get; set; }

    public string Notes { get; set; }

    public string Region { get; set; }

    public double? TensionScore { get; set; }

    public double? HeartRateBpm { get; set; }

    public double? PostureAngleDegree { get; set; }

    public string ActivityLabel { get; set; }

    public virtual ICollection<Reading> Readings { get; set; } = new List<Reading>();

    public virtual AppUser User { get; set; }
}